### ISSUE TITLE
Can't add Label with string content

### ISSUE THREAD

**Issue by mruben0** [babgev/GridForms#3]
![image](https://user-images.githubusercontent.com/5154841/33710782-1a04bd9a-db5b-11e7-98c9-20d495e44c9b.png)

**Comment by mrubendev** [comment]
![image](https://user-images.githubusercontent.com/5154841/33710911-7aba4a92-db5b-11e7-8f3d-75c5ad14ec2c.png)

**Comment by mrubendev** [comment]
Ok, i had to use labelContent
